version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15
    container_name: exchange_postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: exchange
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis Service
  redis:
    image: redis:7
    container_name: exchange_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

# Docker Volumes for Data Persistence
volumes:
  postgres-data:
  redis-data: